eapol_version=2
ap_scan=1
country=AU

network={
	ssid="PQC"
	key_mgmt=WPA-EAP-SHA256
        proto=RSN
        ieee80211w=2
	scan_ssid=0
	eap_workaround=0
	eap=TLS
	pairwise=CCMP
	group=CCMP
	identity="user@example.org"
	ca_cert="certs/ca.pem"
	client_cert="certs/client.pem"
	private_key="certs/client.key"
	private_key_passwd="whatever"
	phase1="tls_disable_tlsv1=1 tls_disable_tlsv1_1=1 tls_disable_tlsv1_2=1 tls_disable_tlsv1_3=0"
	eapol_flags=0
        fragment_size=1000
}