LogLevel        3
LogDestination  file:///var/log/radsecproxy.log

tls auth-server {
    CACertificateFile   /usr/local/etc/radsecproxy/certs/ca.pem
    CertificateFile     /usr/local/etc/radsecproxy/certs/client.pem
    CertificateKeyFile  /usr/local/etc/radsecproxy/certs/client.key
    CertificateKeyPassword "whatever"
}

ListenUDP 127.0.0.1:11812

client local-python-proxy {
    host    127.0.0.1
    type    udp
    secret  radsec
}

server auth-server {
    host            auth-server
    port            2083
    type            tls
    tls             auth-server
    secret          radsec
    StatusServer    on
    CertificateNameCheck off
}

realm * {
    server auth-server
}