LogLevel        3
LogDestination  file:///var/log/radsecproxy.log

tls server-identity {
    CACertificateFile   /usr/local/etc/radsecproxy/certs/ca.pem
    CertificateFile     /usr/local/etc/radsecproxy/certs/server-cert.pem
    CertificateKeyFile  /usr/local/etc/radsecproxy/certs/server-key.pem
    CertificateKeyPassword "whatever"
}

ListenTLS 0.0.0.0:2083

client proxy {
    host    0.0.0.0/0
    type    tls
    tls     server-identity
    secret  radsec
    CertificateNameCheck off
}

server freeradius-local {
    host            127.0.0.1
    port            1812
    type            udp
    secret          radsec
    StatusServer    off
}

realm * {
    server freeradius-local
}
